# 원본의 공통 + prod 프로필
spring:
  application:
    name: chaekmate-auth
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_RANGE}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # DBCP2 설정 (커넥션 풀)
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-total: 200
      min-idle: 200
      max-idle: 200
      initial-size: 200
      validation-query: SELECT 1
      test-on-borrow: true

  jpa:
    hibernate:
      # create , update 금지 , prod 에선 None 고려
      ddl-auto: validate # validate 로 수정 (전체 entity  수정 후)
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        highlight_sql: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  instanceId: ${spring.application.name}:${server.port}


jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    exp: ${ACCESS_TOKEN_EXPIRED_AT:3600}
  refresh:
    exp: ${REFRESH_TOKEN_EXPIRED_AT:259200}

# PAYCO OAuth 설정
payco:
  oauth:
    client-id: ${PAYCO_CLIENT_ID}
    client-secret: ${PAYCO_CLIENT_SECRET}
    redirect-uri: ${PAYCO_REDIRECT_URI}

# Dooray Webhook 설정
dooray:
  webhook:
    url: ${DOORAY_WEBHOOK_URL}
