# 원본의 공통 + prod 프로필
spring:
  application:
    name: chaekmate-core

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_RANGE}
      password: ${REDIS_PASSWORD}

  config:
    import: "optional:configserver:"    # configserver import 활성화

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    # DBCP2 설정 (커넥션 풀)
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-total: 200
      min-idle: 200
      max-idle: 200
      initial-size: 200
      validation-query: SELECT 1
      test-on-borrow: true

  jpa:
    hibernate:
      # create , update 금지 , prod 에선 None 고려
      ddl-auto: none
    show-sql: false # 운영 환경에서 SQL 표시 끄기
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        highlight_sql: false
    open-in-view: false # OSIV 설정 ( 디폴트 true )
    database-platform: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

aladin:
  api:
    base-url: http://www.aladin.co.kr/ttb/api
    key: ${ALADIN_API_KEY}

toss:
  api:
    url: https://api.tosspayments.com/v1
  secret-key: ${TOSS_SECRET_KEY}

# Spring Boot Actuator 서버 상태(헬스) 모니터링
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  instanceId: ${spring.application.name}:${server.port}
