# Production specific configuration for the Batch service
spring:
  datasource:
    url: jdbc:mysql://prod-db-host:3306/batch_db
    username: batch_user
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
