# Common configuration for the Batch service
spring:
  application:
    name: batch-service
  batch:
    job:
      enabled: false # Disable running all jobs on startup by default

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true