# Production specific configuration for the Coupon service
spring:
  datasource:
    url: jdbc:mysql://prod-db-host:3306/coupon_db
    username: coupon_user
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
